---
title: "Research Paper"
description: |
  A new article created using the Distill format.
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The research paper should be in the form of Visual Analytics Application practice and research. In particular it should contain the followings:

- Motivation of the application
- Review and critic on past works
- Design framework - A detail description of the design principles used and data visualisation elements built (Refer to Section IV: Interface of this paper.
- Demonstration - Use case
- Discussion - What has the audience learned from your work? What new insights or practices has your system enabled? A full blown user study is not expected, but informal observations of use that help evaluate your system are encouraged.
- Future Work - A description of how your system could be extended or refined.

The research paper should include an abstract of not more than 300 words. The actual research paper itself should not more than 6 pages excluding figures, tables, formula and references. The practice research paper must be edited by using R Markdown and the ACM: Association for Computing Machinery template of [rticles](https://github.com/rstudio/rticles) should be used.




